// Server health check
GET http://localhost:4000/health

###
// User signup
POST http://localhost:4000/user/signup
Content-Type: "application/json"

{
    "user": {
        "name": "test5",
        "email": "test5",
        "password": "test",
        "orgId": "b0cec438-0af6-4fa1-b1fb-db0e2f7e1bca"
    },
    "orgName": "test"
}

###
// User login
POST http://localhost:4000/user/login
Content-Type: "application/json"

{
    "name": "test5",
    "password": "test"
}

###
// GetUserById
GET http://localhost:4000/user/08c23b25-8dad-49e2-a4f1-1d3dcd47386e

###
// GetOrgById
GET http://localhost:4000/org/4df5fff1-6a93-4619-85da-04d0e954a5cf